version: '3.0'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alticci-sequence-web
    restart: always
    ports:
      - 8080:80
    volumes:
      - /app/node_modules
      - .:/app